apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:NRwzSK8QPB2sKkASvXKa6sc588Dk2WYu2uRTvY+7cVnMeWD+X/FtyA==,iv:A80dQ1Gsap7RnoRwyXwSBbh91oMR9DWhzxOqCkaT1q0=,tag:4c1H+AARxZhF9/sTrGx4Hw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tf87kva34ps5u4nmy0wnzh0epkqpmwuf96mmccm3ysfa2erhqceq67esl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSTZ4ZVpPQ3M5eGVmN25V
            YkdCWFZYU0E1WTlqNDdpZ3cxODN1V0kybkhzCkhSRlVIbmx4ZFVIdUgyd05qR04w
            MlFNT0ZsLys4ZWZ0c08xNWxhYjl5eVEKLS0tIC94NGt4bk5PdEF1NE9NM0tkNzdO
            dWhFcGJEN1duREtyY0dpT092WGVFSkkKH63QBTwZAv571sqFcVVc/lQ6QrkmVegp
            NbKtqtS3BQpZ/oYZthLVpBDlNQxgCaJ5kEeOe/Z0sRY0kdgHryCIfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T23:35:08Z"
    mac: ENC[AES256_GCM,data:ZQvOveI28jlp5GA263I8wWr23SdIvxvvuz9Y/k3RackiQ7btc9kVKFULuuqoohHlPwWV9mygsSIG58RQDCqL6ytFxg/CN5w5BNlpzvwpZnwdqSg795/HbNsJ9ex32ZNsNAYVVTLRT+3XwXhpshXtaEf57NAFEnspFTEJE/p3q4A=,iv:8LHkoUe0Rau7Np/mehQfwPlGiAyvYUXBqgbJ/Qb/oBs=,tag:1H3yWQO6xAhGB0RU3RddiA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
