apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:uKE/Vbq5mR+bVy5AdVSOfgSI9tTGrTp7PZ2u/Bjv4IqDdvpG6OBg6w==,iv:pewslHotSk2U6Twklto5GmI05yl/l36Ppl8dqAzKBkg=,tag:NQj/hLDe2ToojYws94W7gA==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqtexnvrf2r7qdwz9a9rc5d79z097vuycugjy00r9dp0u76r0g4qncnya3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSVJkLzlYMDRocnU4YlJW
            Q2pGQVEwNHpmYUNwaS9OVTFMRnNQTmI3TFhzCnFjZ2Fwb0tMNDVqbENDRTB6UWNG
            WnVNcW10YXFWaW93MHdva0FWQjIrY0UKLS0tIGU3Nkk0U2JldnRKUE44Z0tKemdD
            akpsUk9zZ0VIeU0rdDFUTFNPeVlHbmMK4/rvqdv3MxCl45PDyurdiKzIYIf2YdfY
            E/bRDLqU/Ei6ixzgrPxb954vxBBXfD6jmCSLYAN4FWcjXY7Drgw9Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-15T15:26:26Z"
    mac: ENC[AES256_GCM,data:vkw8Lf0Cbi+eelJrYEWZTYPKx2eLYiibe6r7EtPdxXbJUnSAHfrUmt5gcdeZUASPyNxhAB6Z4mcPdak5pQKInG5b3VJquaVQQWfGXmV/nn0Mqk+qNCK1haDUYDkRpz6YZcZt6CHFHDzZm8xRTb5wBHMAEpJfa+4eWBiYBM37lkY=,iv:G0nwq20vihWu4W4H7fwdCrZ6bVVgRAhaernQmk4sTAM=,tag:k47sRrKZsJXoTOTtF/oFKA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
