apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:85YjUvOkGSphy88+q79caWTUjg3I3xj6CU0JmhZ02VhzFIOmtvaoSw==,iv:eioRllmTANA9EAr2447YoBh0pxpWEQAu48U7SQLzQLg=,tag:gIH5ffTsUlNqYcjidQKqDw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tf87kva34ps5u4nmy0wnzh0epkqpmwuf96mmccm3ysfa2erhqceq67esl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQWI3dU5WME1sN040cjRL
            bWFNak5veHZHYlBpU2xKMnhrU3VzM0gzeUZZClRRVmsvdkhqMDRPdUpNUjBzRkU0
            eFVvZjljeko0d3pUMEZKSkZMU01kdWcKLS0tIFdQWVNFUS9OOGNyMDBrYXFlUVhE
            NWJhTHdmMzJiRlRxdmttck51ZUdtWVUK9X2JCcOqPu6sjXjoZYipXZAXDpK9drOn
            vHaVOAQGg/fpqmg2OiRNi+k05NCpAh7X9caCZEs4DbBCdPP1az5HmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T23:37:43Z"
    mac: ENC[AES256_GCM,data:mC80fAQVG0xh9qz6nBnqjDJDO6BicZJAtIUWExF+/Uv/LDopq+DrxI+kPeQ3f4uCiEgAmzLYZF3XLS8jMGsLTYCpnVBQifDItJzc5CG9MlQLGhuVhar0zPks75K+Klfoey3KO5BWCF8pdqR4DmdIUU9cPxwHyHdU4RN9JYeWkUA=,iv:yNTaPrAo5OfwLKUEwrnI7IsgvP8bjb8u+gIOm9vYYhw=,tag:YOiYxh5c+YMNKsg/33RcuQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
