apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:RuxYGA1w6Epi5k1bcgE325pw+QCL44B+eaiXdUCeWR6dQcCiExXqlw==,iv:P8ZgIm3N9DGLHBt5i1cajLZG/jvFXLgXxz9TT4ahRuE=,tag:nUptDxH8B4u+HVTfBDFXHg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqtexnvrf2r7qdwz9a9rc5d79z097vuycugjy00r9dp0u76r0g4qncnya3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUT0s5MEg4T0xYay83cEFH
            aVlZM3dQdWhOS3I2TmdkT244TEdCdVFibXlrCk93bE9zZlB1ZUtiMkgxNDE1UWhB
            THVYR1RJcnVQRldKVjhaWUU0WWVLLzgKLS0tIERHaE0xTVVQY3VxNFc5Kys3aUxO
            bWg4djNuTTVTLytyb1c3endMNWY0dFkKj+DEGNSenBixxPoDoDkgqGT5nQE29waO
            pV3QCr4AVWE63OcPcO0YFF7Q/jukbKhAo2a2auThzhfsxpCZtIrwUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-15T14:14:24Z"
    mac: ENC[AES256_GCM,data:YAOH2CTJnUQ0WfDYHGTR77jHQ2RAm5cvHeT0jSEYOR9qA81xRGoZxLXZ9wQVgufO44NY7pxAiXxYWTdF5dyJ5vp3ljkKebEgZfnUeYCfwYQv6TJcMZqSfigJHb62Jp6Xa+af4LHZrWg83TntqZfKOa9UqCE/E1mcDeOAMmd/mHk=,iv:WjwPVrsM4dRHQS2UANuk09zmZ+6LgTBba08/yWA2n4I=,tag:/FfYj0+FH5ho4zKlXciQSg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
