apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:DWPmX3UdLeJdJR0/3NvJJ6D7Cum95japtZGWVn0gACCbMXSslk7XSg==,iv:z1LVb0aHI/vT3Z/Em/nlSeD4Kxg66cINo/FI2QDS+20=,tag:qtJvL7/3BchSNm3vbwPOjw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tf87kva34ps5u4nmy0wnzh0epkqpmwuf96mmccm3ysfa2erhqceq67esl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabk5yTzF4UVZQRldvb1Jq
            UFpuRktlbHdjQkg0MEM5SlR3cWJPQ3FRN1NnCkQ3RXBTMTFzcVRqditCdW9GeGl5
            TmRkQVlhUjBobm9ya0VBbDRGNnkwbjAKLS0tIGdaMi9GalphY1k3WDNXZ1BqMVJm
            a3ZJRUM5Wm9LcGlhd2ZRME9IQmRsaHcKSrLYpORZnc2s3t3sWWvLQBjSR2265Pga
            sLiMz/hrd0bn4GVlVgUNiV616wQyaUajm7mvflqoLbNnbQDBCyFOYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-15T03:40:34Z"
    mac: ENC[AES256_GCM,data:5JJmKvAwDvGQCcPu6qVkSxaesKxF+c+7fWsC+MmCMgE/GFqzjXdCR3fCrBS3aU29XY98uDuy+VKoApvvpWazCFoPrL3CVsJusAC2GIruLd1RlMleCDUk5W2sqAfiutAOK/ISZjmQNeQI3kExJ8LHHUj7DUupbYvESXuaYbw5TtA=,iv:G6IWoE11iY2b/zA/edV7sCBuEu45d6U5i+r/cEN1mRw=,tag:6+kSsd4LqM8c17G1pG4ryw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
