apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:dAEPPVybJTHQFRRTfHv0QiFBGJJEkWZJ6GEgdn07Jfc/+x0iF0wfxw==,iv:4k6EFL/KrCDHHIZW0s0085jN0y1JIDv3Uy4VHWtW1RQ=,tag:GoHWNszNbgHoFGYhog8ZVg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqtexnvrf2r7qdwz9a9rc5d79z097vuycugjy00r9dp0u76r0g4qncnya3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByd3pSeXYzT2N4QjJmM284
            UTN4aHIrdkNBcTVUYjNjVmJLZzBIUW9SMUJNCmxBM2ovMXBJcGo4V0FYaVpRemVE
            VHlDSGRkVWZOSVFhWWVTTmo3cG1XeFEKLS0tIE4xNE1xeHQ1N0Z5Um9DUDVPWlNU
            YXEvMmJseTdNdjRSeHJTM0k5Q3lPbEUKziGJdQMrQqLl+sHm5hBhAJS0HSNMIgwX
            drQQ3hkzuerR9SzCHzdVznakQ5ojd09Q4EPaFnhL/9nG35bcNBNVXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-20T16:15:57Z"
    mac: ENC[AES256_GCM,data:orpe8uX4whqaOIa3REkuCgSvIo/gKMRInZWQZefMnyQWc5U1BN3Al1Jr6kEybyE0U0CwCVUGKb2FeT3qDAOELBGauA/Z+cJ5kwgfITb1co66ndU1L0GktE1guCxhGAEQjsA0cvdC2UTJ/qbpzf4+m2bOTMtLCvJIPpgiXY+LAxM=,iv:ie5Ny6GBlsiezDdFOtPp6A8hxh4kunrla32SLFSEchA=,tag:h0s5xyUKqYLVwPmY1wg93A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
