apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homebridge
  namespace: homebridge
spec:
  interval: 15m
  chart:
    spec:
      chart: homebridge
      version: 9.2.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    global:
      stopAll: false
      
    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0

    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                HOMEBRIDGE_CONFIG_UI: 1

    service:
      main:
        ports:
          main:
            protocol: http
            port: 8581

    persistence:
      config:
        enabled: true
        mountPath: /homebridge

    portal:
      open:
        enabled: true