apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes-dashboard/ks.yaml
  - cloudflared/ks.yaml
  - ext-service
  # - mooneycloud/ks.yaml
  # - hass/ks.yaml
  # - wg-easy/ks.yaml
  # - homepage/ks.yaml
