---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: speedtest-tracker
  namespace: speedtest-tracker
spec:
  interval: 15m
  chart:
    spec:
      chart: speedtest-tracker
      version: 6.7.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Chicago
    global:
      stopAll: false    
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                PUBLIC_DASHBOARD: false
                CHART_DATETIME_FORMAT: "d.m H:i"
                DATETIME_FORMAT: "d.m.Y H:i"
                SPEEDTEST_SCHEDULE: "0 * * * *"
                PRUNE_RESULTS_OLDER_THAN: 90
                DISPLAY_TIMEZONE: "America/Chicago"
                SPEEDTEST_SERVERS: "32338"

    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-speedtest-tracker"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"       
    ingress:
      main:
        enabled: true
        hosts:
          - host: speedtest.${DOMAIN_1}
        integrations:
          traefik:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: cloudflare         
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: s3
            dest:               
              enabled: true
            src:              
              enabled: true
    cnpg:
      main:
        # mode: recovery   # Set to 'recovery' when recovery from S3, also change the revisions 
        backups:
          enabled: true
          credentials: s3
          retentionPolicy: "14d"
          revision: "1"
        recovery:
          method: object_store
          credentials: s3
          # revision: "1"
