apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KppAn6Vs2zlhfFPtaPGJGI+xABh3mHHoS8tQRI51P7Q405YHLTEueDh4qqztImH+0/tewBE7NVjZzEHDOCEXusIIl4budFThysamxYmbB/jJJHQ/XmK8emy4OnNT7pA+7Q+5iBK1B/actWWAUYRq5Dsb2fpxT+b2uePwcNAxz1fnmc3XLeEZ+Y7b0LcRQoajIazfGmpd9F6FTFqhfz5Eq7fOWeusgY3Pvb1asUIAFWogWRpBEeaUM34POIwDb2GDXF4BC+IJhhemztFxD6oYB5KNH5NfwXF9aXCiJypm/bUuJLvaMruJ3qAP9nemxnun57iWoWPm7NLvyf/ynli8/O2qu54vayZk9I4JcuU5eXYD3VR5CYsRP6Cq2sJx40FT,iv:Ih+7eHlSaZgh2gy8Y6NnJNjE3sfR3wddOgnes1Jhp+0=,tag:nezz15mNtG7rObh2Gd+0+w==,type:str]
    identity.pub: ENC[AES256_GCM,data:ImmLcstz6gefvVL9RImERjNbmJYi/c7nxrr+FMZiJOctKTElsDTNPksPP5tm/nzTKXsb/vi2nSOFF2CW20D9JN16lZ6UO1coTy42JhRLymlYlDyLsXbLNiLq18orvRcCXmDaBTsfdIsrS+qVZtw+3aWd6p2C8cizb9oEwsN+AgOveo0Uf4hDHtWqBIjlUelUOy2bNKz6inT+kTEnNSenk0BdYcAmQ71KgQMznfDc8/7kcOHIiI7GXnw4pju08WQ3/mlR3awbxS0flhObsQ==,iv:+cHh/MrTqODgDdzLU0Dap2SqSrs3H+1hh6CJGl143tk=,tag:xevHtd79rjOlrj+uxPXocA==,type:str]
    known_hosts: ENC[AES256_GCM,data:Uq+sXE/RjeiFemfd7y6UBs0JtETCji1i6cgebl094lCu71kaviGmXvIfSLGQGgA2VMgia/1T73iLY5MYyt0CcvJx7GCnNFIEldbtfRisjPqF/gMOa7XmrsKRL4W1ETtHchftUnetqLAzVNjXzIeykEWAoEfZrXqsJpRc/FBQlhAQQRAVeVy4iDgZGJ8SnsKBUWRlXsCG/YhCNJ4T/R97uUzd3ByABw7tEBvJ,iv:bdTQIJ5WtaJ3PHLW3+CihMe559EwtJs85f6rUigV8uo=,tag:FDdyezkumqr/6vybj2GBXg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tf87kva34ps5u4nmy0wnzh0epkqpmwuf96mmccm3ysfa2erhqceq67esl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYjV3YjVKRC9mR3g3V2s2
            NExvc1pzcFR4SlZ3Um9BdE5RRHF0TzJ1QTNvCjFHYXVwMmd3NnE3VWdvVDBqbzdL
            YzVGMVBwcWxtckZZaHNSV09JcEk3UGMKLS0tIGRIQVBydUgzcnZnRGhGdXJqNlFp
            ejRJaytvTVhtd2Y3eXFqZUJvdEk2YUkKfktrPHGh6plRMl6/ktg5VKuHTxk1AVOO
            y7c+6XGC2+e5Hj40Xc9POsgUPRTptHxoGmBYGUfn6ebE8b1PN6j26g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-15T16:54:07Z"
    mac: ENC[AES256_GCM,data:H1YuIRLPdZbKv9ykm8p6hZiRFa7cRKJ3wmeAR6gNWd4n7feBDRUl9PUfVBYVdpDVN1vzbOJUqguEHAOqAliQD/SC1IetlVOMQ+cc9ssIKZPcawiK+95/qJg0456Rh+cdMehcCflv3RO+FugY1Wznj6SpCkWte1oKMy2UaDfnvd4=,iv:qhvJbl2JUttrPYByuuw/cIHAWajkj5YARe5OeNF4OKM=,tag:64hLjH10hgiHQnnBBHt5wQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
