apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9AuVHr0KIoGtyvVdmy0CvMMWHums8YMwt83gZaq2O6dIB3VPzUD8XGUEPNYrtuY1XYxgTnVlbhr8N7E2PD0PaKOTf44qMgR7xh2EUtN1GEfciKOp5AseI9Vr8srJramsyM3I2irIOjYd/08s2EdQevA4gHvo+q68B7h6WVrosAEwHAj2p/+zfu4MQKOksZXjYvm5qQzXrdwK1M0mqkbrxmuLmQYkDoLmVPuZba/T5e/F0Hh15ZfDsG/gyJYLUHiDNmZuffKcrrOUGl8BI20IefZ693INnWS6F+iQyRBuC4+4gnuLBWbGfx9wxt2ncyq3CO4Qi/In21pzTPaHJ1hVB7TN7SJ7FcFTEJiVwPEIUuSt+XK2cEJn0hfM2mZ08dbg,iv:bvT4BQLfOuyJDtU7JVnAGq+rgIS4NrMy1nOTGGliDNI=,tag:+OLbtjgJ56jH7IYp8sp/MA==,type:str]
    identity.pub: ENC[AES256_GCM,data:ja4HxEwthHqldyPGitsfGgzffSGPfnpH2XNb+A3EFGZ8+5a+mv3aw6ev+iV0UvvRPw86+bWsMUqkazkQxV4Ftjobe/xS9Kb3Of5bQyLqHXVNYE6AcYaWrCkDh+qkZBFquyFbfyCB1pPS9nn/ZBiOd6IO9z/C6bRA7ov+ZhFUHJlUVGnpIWhOrxqpgGX4ttlFXDYrMUqQIi046j6LIdqeE8uV5NZ/YI97sTo6Wsx7ma3DLtqg0rggMXZb3xaMwYJab4JtRwNHD5CC1fhmyA==,iv:DHI4tvrVTxwPl39dCPiBlIybAHZqTR2wvd8AaH/c8Zs=,tag:PbMj2MpA/Gzpen7CnP5dCg==,type:str]
    known_hosts: ENC[AES256_GCM,data:tUpMYIit2XDEWNF2IXpDTM3OeuxrSf6KFAiBCzff7UfPsYdcvXFMEOMRUX9g7Hb7dnEgrryjlkNlMAjDAxLxOktRBgK4FqZp9HM390diKcT723rx4Vr0KKAeZDni0MM+wsQsQ6nZBzZMA6j9bkw5K0dWmWqf2Bc7WQROYA/FQHjqi5xWHM/uLku+ztaQrEMPn66JVi1u69iAMbRQ34puXCUTcXAeWjGXH+Az,iv:w3u3wTRkx9gmrxOgWv5hQdCC2LUCh+J4vB+RbXY5K1M=,tag:0TfaVMA1LaJjtqFiJwfmRQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqtexnvrf2r7qdwz9a9rc5d79z097vuycugjy00r9dp0u76r0g4qncnya3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cC9xMXByZWl5aHU3Z2xT
            aVNLOCtuSmtVZ1B6N3J1Y1lka25uSnl5SFVZCmNLdWVYLzVlWUIvb05WQzlmTjVT
            clFKNVl1N0tKNUowemxLZG1UQ0VXRGsKLS0tIDM2WkRmOVdhNGpoUmJHV2xDM3Ur
            c2E5Wjg3dzdaNkMraTlndVpRdkRkVG8K1lRCQZ17S1ArUS5MEf+n5epAD9XZI/Yg
            18NFlCuQgDmK+ngrd4W9/OTDD2zmfp3RDQ54kMDy4tXECeoj/duSiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-19T14:16:21Z"
    mac: ENC[AES256_GCM,data:tFz8uduqW7UG9/rIt01nuxv70+1J+U1JyglBhSmZmq943SWuV+d5XmeWTRB8Ip88HFTawlwfMEAq14cWpIZ6LGwPSUd50y/hyixoWlkg++t/vTAj17e0b15QnBCWq1VAfUzOebxPquTqU1JOkgYXGd+d58BfOPKquzcQpXuNO8k=,iv:RSiQFh2CRzwBc1voK78GfAKB4GF/f3WW09/COKueFSI=,tag:xw0JmRHRXSbl8SGnXT64aw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
