apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:CrAKkM85npNVe6hXyV6n2m5Hs5HpZ4GVzn8BPZARHbjzRg6wm4SxEPzpWOhnvPwoIfbm/XAcz5082L27CmGUXJUhTcsGSzvItlzgMBZ7dsYEihAoHfjbTTaqW5qiKZy91Ixmxz9J87mhZXGlWHnZD1G4MupOaw6ZlTwVIlo+RKhsIuuzt6+ffa4a696fr4SiV1jTrNFLLTdUrLuJHFR5Xu5pThCzpHvFIRgz3hDhW3keYFRANPaI0cNWR6XLuwbu0gKjqqmiAf5qyo2T+vuYS7Ijb9Mnt211uLRDtM9cyRXN4k9YFhgsUO4nEW5jRxCnpQXA+SuLFuPgIPKypys46hFI/GHlxHWstjqpvRHAr2XGPOSbyugScmJloLxx9T2B,iv:z3TBp3/L0k2JzQX5VkWBIdJb0MurkfdWTxn01GucpQI=,tag:2JgDt7c2RYaK/7l8QD6U0w==,type:str]
    identity.pub: ENC[AES256_GCM,data:8vyX8lRvUqHOL9pzJ9oJ6danw4iJuNzQwNjk2Gdb8OUwWrsygJhlyXK1WyrY9RDh0vz/mJYuiEHAon0OOMfkOpN7j4/OT0VxvEPXRpCY6/2+UOJvKivk/ZpOIad6+H5rtVmjr7d+59tO407fBbIm9w/9ydL7ovNvVrFUI5kPI4vmuei2oJSVMKgwfIG1ioE1LCwLSM5+Gu7BuPJPSbQ9oIxqHj3teVNTeJUPv7WiMI1Fpn5F6UwcPI2wV4yqChTu86M0w3JxhlkFPHYiJw==,iv:dZfmeKoOf/eVlhnm+2hhdIdDKIGP4st76IAdAYwYc8U=,tag:jDbLzVZSJheO4DcC2Fm+Yw==,type:str]
    known_hosts: ENC[AES256_GCM,data:c6dNZT6O4lwC8kq2TuEBr1Vkg+nvg+VKqLXDGBJfpGYZPoC2hgf3dSTsBmfkelW1n5x+pzyBvI0VtXhM5MBpvYBz5r5Sgg+dXfEzTwgYGejiUuSyyNy2wgPpdvPu/JaZIMa2CGTPx0IrkteVv+DJPfEOnt4tJYOZRdUU+1tzfU72dYexSp3J1WBqv6H7C2dwbgsEqrAWycbO3e77uhJvSPcFowrLcGPEX207,iv:eTSnpa6W7h3ukDAYwBgoE2dXdNR/WHHwQxkwxMDQvgY=,tag:1i5ZUZt/PbBUUACOE0Yqqg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tf87kva34ps5u4nmy0wnzh0epkqpmwuf96mmccm3ysfa2erhqceq67esl8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZEdVa2QxZFUyQlgvQ2hP
            TlZ4cHNDQzF6YUxJejhVb3FnMFYzeW5MK2tFCkZCdGhCUUFSR2V6VTBWcW1LR0xN
            UUJvMSt5R3I3blJJcm4xVnZ6WC9nVlEKLS0tIFZ1c0hmOWFYWU5Ia0RWMmRFbUMw
            V3ZmWEtqRStQREM1dWZQaU9vZDVvdmMKhqoVSpZLNIs/inS/ft3S351m2ZIOI+b1
            nZt3LEwXjpwJHa6pyQWGGiB3B2O0AsoUMThoTY3wPL4wyLwTRPfU6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T23:08:06Z"
    mac: ENC[AES256_GCM,data:QXA0PkZarLTd0tOReNCcYHBbhfX7DMtcf+AXuEW6wF5s6vLVG/c7/HOGaOE+5pIUVTTr/pm7gL68DRaz1hOae5nvaxu6WfDmXJMe/isvKOdGMq7PTwMUJIOqt9y6wvFQgizYWuagVGoNelY+lOrfNYuRUvU7BWcIAiA9Hx8/+HU=,iv:5Q9pXI0IU/q8WULDM3V0sB7Le0F5RTw0P4a7ibECF94=,tag:j1zRzSTXTHMFj9HkNJ0NUQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
