apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:SRqJETEBo1WxhL2o4jUToyWSFgiaADOHhI3kPCIw7V76XqfFssKjFcGAMHDT3NmALLSGH438zcA8/VVp/mMa/JDJPsS+eC/IIu2xhsslpK5YOKJm0NlMhI8dix6ggwhO6GHoeO+Ce4UxCeN3scX2I/UvrBBMT6vcXZ2xgj+CccPZOGy0c21V/Oo6vp+qVgGQcCVFzxMp1GACIRnmZk+4GfqtrBvbICZo/sHBsp2Dn24f5muiAnHVL0yekooh0Faw4XHv28kIlkfHGbO7rCwAuJupzXzFgaWMtfyaKs7vy4ehVhFpxfjrxtDGEy1K1UN6qpi0EUjGN3TDILOcHn7Q0ZvzlORiZEEbbhm0UMBEhnEIZM57rDiVzUh5NvMaM5LC,iv:uZotDpQt7dSGUqX9FyfLAh5cOlH0alcFib0RBImVu9Y=,tag:R0MTvitILkLLWIk71v5Axw==,type:str]
    identity.pub: ENC[AES256_GCM,data:c0aGvm3mHvy/50qoCPFpcYLeH9f1Is6wvY8VZEKCBvhDAPAf4uegSiSAvCV6qcCuEJpcKsd63JMIXcmZMGd51PHB6thitZfl4h7srlALJlVw24+7yBL7RlrSzSpnznzlsl9g4JK8mGCOJZClojNaqO5xDtWzg3KTYxNH3VYccyuS09AIasNRee5RObD7yk+IMkFkfltLiXt7zMB//nE0Gx3N80gtnjVT7OHvdZGxGO2h5+ZIorjcJB8NIqPAjnCO04sTl4mvV2mCGuOOoA==,iv:Yqvb6eeZ3vHtTBtSBGWJhsGCoSAsewF7X0RWGjW7aKo=,tag:eXYbZa367urzUHx3FP5Qkg==,type:str]
    known_hosts: ENC[AES256_GCM,data:UWKjqPGQ4kbE70xxZ4LX3N2lhr5y2aBYn3TnZiuxrco0y59o6b6yGXYqsyPvydVJrESG7r4egW9bOlLrX9V/QLS9HzM/o3hIWK/jmVOo8ac1UeEHaaUR03/rE/FPmxwAgg3l+Mxz2ZwFOoNH9TwrUamwnIo2IHXtMblpwDV2jEvopme90cKaG6gW1Yf7lv+2Yt5cXRk3ZPm+gwYMaMY2t8mWlyJV+5hjk+kL,iv:4WPCroTonCLyaT0Msoh4yIENoMC/uz7Ph4YK5YUHLBc=,tag:2UPaMhAG8rpNvtDxCvTrew==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqtexnvrf2r7qdwz9a9rc5d79z097vuycugjy00r9dp0u76r0g4qncnya3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNXZwM0ZEUU5hRG0vRktF
            ekZBWlMrcmVmSGJQcmN5YmZmYUtpZHNqTndVCmhtaHRKY3RURlg4aEg3RGJNdmJx
            R2lXSzlkT1FVTlJsUW9OVkJrUWRWN1EKLS0tIDZYRUVieFdlY05LSDdkV0hTZkt2
            d2x0U1Vrako2VXJsT1ZyZW5vaXZTY0UKU1EAtd7HAE4sh4YGfjukBV+CJh9x0gKB
            9yZMjjFbety8aFkm5GhlE/evUgbTXaZY2PiEebT8tWu1rmbzdPOHDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-06T23:25:43Z"
    mac: ENC[AES256_GCM,data:R4OozHQdYyiGkMO8r2WEUMJLIlI6j7kNXH7N+9CLTdInqEUHMwIUew89ZXv2IlNWYUsGfInexSJwaPq/PHPJyvHSacrK4ADWC7T/dscknJJW6pWyAoCxPFti3XZVtItHNm4M4rVumCT0NSs99U8CLVCsDF46w60jWY93f/153Io=,iv:6VoEYlrYAJJ5lyeiiKVh0BlkfsWEsYteYe3J1RXsPdY=,tag:KgDTMBkvGIL+uoJ/vPfQzA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
