apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Mqtb/tr4c/y+fIB/Pe6uGS18RPOZkRqO8S80Uh4r1loTVahDeK8YfES6EY8Lxxr24tI6Vifcx/jPDlxPUpSSNle4YtUmS9TeG9PjIcuIUAAqfQmhIYos6ZB/DHqfeRPbAzemeMhEGO8xzzuA8aZxUivHsOKnuzxnQuWEryHIyZKJ8/r6OXTsRNyCt7Eru3QivmVZWmcbKTKX8qcGehwXhgE3rP5CJ5Dah90/ytbXCBpUohwLGav/ZJsEe5lFmR/so7hYoHMjtWH2pw1gSbe4N397+15x/rTzVgIjhI1fAuC3KSQUu8DMQmNklwrGMpq1PI2GTYZel/EXKWywCCvtJy+b2F85HiqqYdEAQP9HR/d3MBckX7zgemObKZXDJJXc,iv:lqGIQC1rp1y+zNymvHr00iMQOOLhspvXxt+xv5Et26g=,tag:dPiiq+Y54p/KgleMLWiVKA==,type:str]
    identity.pub: ENC[AES256_GCM,data:wCL8jdTFtirXUc88Aik5LDQL8+Z2/Kg8ivIC0K6mZPdGyJwVK3S1ZBeXAJfl8QR9ctp5tSfMrGDvxC8AWaJdP4PoxEiV/aLAmXzkcKbllQ86R0nN5/jhFeiIVyO7l/uKbb9mluLKKp8MA60qZzQOAfVv9vepPcQ5+t4lZMar3H6YyQ1cG97DiC9NrlUuJWuyRJMBu3VzVIjZZYueyr5PQONgfld994TtXjJVMjzWn3MmumxW4iQPF2wSP6yXZWXZG4xR+DraifpjKClR8A==,iv:QTIKFXEEn13JXpYlsimnZeg/Nacyn89cWlXhBFYzG0E=,tag:XaTlzjdsKIyJzpWER6WPIQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:VPJEfhNusUNhBCj8WOB3wicPRH3OugYOzEPLGfgwjqfiR+f6okTz94faMi4gATN3gykTjdI5EytZ0pC4KvRqBXYzEE3afSgS21PhhdEhIaNOdI0Oyp5cX0YiMXpnMHWpQrffHuyqAWwB5K2cm79scfyShl7R35xJSEkEe3p7Rjs+Ce4Qnp1MxIYjaUM2pfeBerxhpFBlAEen0C6/eVVPch0W3WV0PPKaPV+q,iv:dU/cDUJzNj8UFaY05IRyZ+85b73CihGWkXroQfakRJU=,tag:+g9ElxuLmg1Yj+urjPcPzQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqtexnvrf2r7qdwz9a9rc5d79z097vuycugjy00r9dp0u76r0g4qncnya3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMW9xdkxDTjdPRlVkS2k5
            OWJaTFFqTnR5STA2RExkcjd4enVIREk3ZFF3CmFkMlZkQnEvSmJzSVg4dTc5RTBi
            NVNQSE0veVJZWUR1Z21SOElmbk1mU0UKLS0tIGJmcGdHWVQ1UTVlMnF0WjM2SFVo
            aEFoTU9QMDY0aDEzbjRwV3lMVDA1QTAKMfP1bxSifFdsSBb8xfgZAlyvhxXKlc+8
            jw4kM6mJD0/+8pXqd6tJOhZCNhT3Endq223leReGoDeBr9l1sSRDVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-01T22:01:52Z"
    mac: ENC[AES256_GCM,data:LpJGT6NALCOLPlFqXjU0vdVDLjt5MzB+nJSP4x6/GnpeAZBlOmoEkMbXtLy+qDygX3DRMtKhXtVv+RCGGDq/EoP1IVKmRaNPBxnVjsaJMCGBTRKIxKUOSWTYW+apQ8IYidfi/In0egaFR6nk2736FlUfcQxAUocXGlvnwlunIAM=,iv:YzK+nBV9aZI+XzLIG3XAPlvcMNkzAPCImzEDv6HMLsM=,tag:dXz8rP9HvyGPWCuWrZTQZQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
