apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:mRTVnBU9Kfptub/a9HWwvJX3MFfMvQyFu4w7Th26rmg2IwhvRkgdbcJfWLMI9KhWqzhSp/FcjY5SqLPQZak0oNyGVMwavV8UDGMMrSuOIIPe0twf8CFbaOX3IaW2QssEL3r1hLzha8GFJEk02xUQCl204WBgfPrVp8JC3UuWpXLZZQQDVOWR1vxC3Jbr2dFHlFXEhn6f5Qa0mLPsXLk1owrHA6Jz+4P1C2ndNBeE2IFdvNH96TwF2x38CS0uSOEUj3zJlJnCFlPGn5Hgd5NWfWVZdy+bI4cHIoOs6bgpoUhJZ0CDJZlL5hwOMK9kOSR89BQpZ4+HSDi34pEqnmZ05XAI/B8NUxZlOHWSRtVA1NadiqKS6uA8lho6GX9U2UVe,iv:GXLNlZXSMYyLivCqyr2ZpdUGCX3nbj3JVD/K75g/W7k=,tag:zgmOyOcE+uJBpRO1yTm0qw==,type:str]
    identity.pub: ENC[AES256_GCM,data:rn44vKzV41DQJ/8zA8MWLM9bfHZhm16lK6qq2eOIyieo7WwCqcZLHTeopAK8mrWIzkXnuqzqKL5sA0e+TDZqZhHcsnSDO1bCnJ+b+Yc1nse0uuwQ73nwRwhvGaRQqmSwXGMa3JrzCW8xGYzq4+2KLthPX0ePlF/4dKz4ABCJFV3kQhdl5P8a0fCv+9ROQzRRArEo7d7BThTrg7rN9m2AFg/kpCCEBW9VMhRE2iG8rATV2KQJQV/papwsCnZa6koCwn8Uia0vTg5yuRsRjQ==,iv:NymbTUF2Y/0mzDz899Bkq48pkPF7QOyxUcIH8APSSQY=,tag:hGx8d9a/2i0rGp6bGQ/JWg==,type:str]
    known_hosts: ENC[AES256_GCM,data:lTgSSLtO//qKGvoprttIAlxEIYU0Ahcsrox1gAIdaZzV8THxeU3GV2yqcQY/+kfdk/poK3KHhsnCRAVv08Yob1ENWE5oYzwk4B/6v7TTXaaNkTvEBGtjZFdMCCpSEIIjY+PBP+9tOEczmzsmgjIel2d+ueIqiDY6CG5h5F6wieBvSOvqYgDBSgBgJi2EMuXrCIlSIIN8EhKZxypqyGgAgopZTvMAQ/YaTDlv,iv:zdBP1EboxtBM5kPgE0W3w6zcrkeGomOOtNIpiNCZZHs=,tag:hogMMbZpHF+hBesrcanH3Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqtexnvrf2r7qdwz9a9rc5d79z097vuycugjy00r9dp0u76r0g4qncnya3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WFNJZzN4RWIwdDAyRFFz
            MWxvVmM1aXVXZUQzdlBiYS9rZHB1ekprbzN3Cmg1U21DcmtHS0U3TmdiS0Z1cURJ
            elJBbTRUTjFhWktOUjBWdzk4OWRrcnMKLS0tIDJpazFOT3QvN1VQaWpXTGExYWlw
            UWpoVkZBUzZ0dlZycUFSK2Q5K2htMlkKlAyDpP1sfd5bGhAgh5KGG2xbiY08/2Sh
            l+8GSYV7W2/FJVUZvF6chBY6TC9hL+/KnAxvq1DYD47qfMj0JkY7LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-03T23:13:09Z"
    mac: ENC[AES256_GCM,data:H4RPkUhm3aOXa7F9y/EQTvvr2MbwI8r21GdNdW5S5XVRBZurkQeCykpUYnNNSEOrHQwvm0KHGFrxI65EBkeH2LN1JXfSo2A+F/JqBvLV4iMjK461xlEzya1cK8SgQcDBOzZ1YBx47Tlwkzu7anMq60eWPuKTJmY7MNgYUC2m/V4=,iv:Tnis7cZS+lgINSVvBfjlyD1A6Ily50yUcfW49yd7Yqo=,tag:l4lWGeI09Gw62xC7SYOrAA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
