apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PCShVKhc4RB5lPJgPR5MGVcDW7nCx/FJcTqDRstZGfC95+xgItB23X6b5Xv1kNoHfDqK0FCe5zCdQ7hB3kzsu+AKQtkwYLxCSwX026IVL2NEYIB8ZOb9pG5KK0pr39xVwf1Wk+3rCtL01drSPeOreRcgLdr60biPYIwv7R0sSioABSXs5pwqeIFEpjBPoMTJ5sZyfnGvLBMHSssF7SDWihWziUnJOCfh0EP4ixsExZO+GGfmKvuVi+8E7FrdTsNaOp0KETFLV7upDcG6fsClPH04c1kQquifixyR03I4AWX+qzY/QiNl1MZo+mXvH22aTOW2X/hGgyQDBmT3jS32SGe6uK4vrco6HXfsLweU7SohwS/Q70+G33PS8Eea+Vnk,iv:dpiElKgm9PP3uS3kzfBmUxY13a279IiKjip8tlBGrgY=,tag:96rALQ6HCW+uGO9a1EEDBQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:o/ESkyAl9If1Hhu/LFTpCKbP6zHat3cYibZmAiGRvwU07Rx3G50UUeiWOFXQ0r8oEd9FKdAO6M5zeB9nExn4cZfAJyKwTCiObRD2Cv54EwCEN4k5Uxonk79cMXbDC7sOtOQDQdtrHechwlnsWvuDxmpvc6G/rWBsFKwpNRh0s8LxXe1BoQgZFlJlKTGpOZHARiJsPGq8BzqxY4KP69z1JODF2rPCGnDQryRzF3c82Jg3eLrbRm1RnB8HB+wiRdAVhUTQdl0STWQCdcXamw==,iv:e4g+yjDRzfz8E/SJshfmtJCc5kuWONbqIcbU4c+S1ec=,tag:HrqYEc/vV/4MJ+lXRcpwDw==,type:str]
    known_hosts: ENC[AES256_GCM,data:CWRS9HX3I2SgU57nkbMwiJMz8lFFKqe40nOy2dgpWxVl82bpnvaaiBrWTnCONU0aUH+GBNOYL+YsJmPycIrNYz8YdA1IyWFGPeP6guidynZIy4Dj7puQ0yPFboznNd0g5gOAfnmpxFL6rC//A3qLqWUCDhlTq5KFu1jrvw/x2kHwCCFbieul2/G9K1PjBgvkX0mlWbmYBpLWZmIfyA7ANQDBOzUz4ESv7CqE,iv:13RiQQjOcuEzg+/hFDmFhJuJ1Mw4UPTl+H/WHxMG4H0=,tag:0YQA+KHgahs10/QOBf2XBA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqtexnvrf2r7qdwz9a9rc5d79z097vuycugjy00r9dp0u76r0g4qncnya3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxalRaSk83WHpDMmdzRjZV
            aGk4YzZmeFFOU1ZpeW9zZDZic3JhUFRVekhBCm9NZVVOc20xMHg5aDc5UFFOdmY5
            ejNvZlFlYXh6dENjaER5Vit2dHl1WVkKLS0tIFFCS0JQNCtxc09ZYU1ycENkRjlx
            MjV5dCtXZzZTcnJETS9DRmE2dmpsZVkK2zBUTONygA+Fs5Vfd330d551uVvKRTZA
            oAqjNWUV0wd4jV3QIeGNDRvw1C4gpT9ZAP8TSI8L15VClogN0FL7oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-14T03:02:04Z"
    mac: ENC[AES256_GCM,data:N0jEOkGiwIz5aw9dRxIswCabt39tFfVnfjaJlqERyJYqP1yOSZRB+sJSMf92w//XZJe0j37dxb1hagbbiE4OTwjNsN1EJvuGQKzlsfAKiJghQuP874FNUEMQDelctYr/RBg+o0JVKeUpu4o/if7iQzjLKV/RmjlJgIMouDOnjbg=,iv:YtyHnustfzA06Ne12MAPoWbYprRP2FFT3rp0MiX5Yqk=,tag:ygxdxsu0JIXx6Bj+nxaDAA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
