apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uM0Mm/9CluzyvIfnJX9J2RGvU6R7F+AqztTK6KjDbreIFkZnczatizDsf3aW1hLF24C6TAyO71XW9M/NyJCZeLkQZWFIv0hT0a5K+uR8pZ/8BDbAZ2T4UknbVTLvo3jj6+HIzbWsT4CyJ4Y4p50Y8BLuWVnOD+6Mr6D5EYoG8S6pEVBvIxU5mCI0qPaVpMukpd9xj+isc7U0dhVJlPT9MJRBRHT7hQQQGzM2g99uXs+g6ns0ya0uJtWTkQdBVzsQ5ZCjrZtEUzf5PfPmJ9tRophv/jMOONBi4JOb6/NrU+deM6nVKUvx8WdRkohAj+VJrDNoruOFILIrd8zgw11uXp0j8PRnjVoeOaHUFs4GjGs4n89J9Hbq1tSq4UBs94hY,iv:o8mz5HU141Gtmq+qLkf3yQypcgaCvRKCn11JM3XpeUg=,tag:mKqplZsS0Vv4/0NNbpmhtw==,type:str]
    identity.pub: ENC[AES256_GCM,data:4GHFQcpomDUeDZiD+ac9a3cWaUDn90TowutDtdqTjqhrAsm4AG/MnYEXUX+hYH3BAVoU4D9CcoVJgiQ7Kh8aco7OppDKKY9N1lc+k4MWH2iqk4JxA275aSen+25fJK7Xxm/SMXMsYZ1clZ3Ft/oTWohBWa1RbB7Nrh5NGVyw2j87SwE2FpuULNJvMQa1MNzyQQ6Zktdty+BWKPEHTnqBRTH+nY35NuST4OQ3ewt74ASEgqbXP+Kdl+jUPpgT8LmXBoP8SHDaF35doPtYAQ==,iv:1nJIySaLsj6kZt8iPjb24c+WQBioMFtN8ezuslyS+jQ=,tag:nHdoztxkPgTWXBymfT7xDA==,type:str]
    known_hosts: ENC[AES256_GCM,data:a4ZciRttjR6n2OV2AqE/5kGO1HxP2O22jLnpu010AojKvohio1OMvuwhZ2idkfMf+2MfwffUI9Eo2jILWt89OlsAjQVQ5tzU07WNVfpYWzMupoUjSHhVxemQi4+8ukGITdX6lJnzQBsmw2tGB8YnRFMPUBa7/vdozabSZ7pwj7Z1v75h3j33x/31pBgsd/hacVrQx5YMoEEHKDxt5Wm+spuPIHla9D0s8rLL,iv:V18od6pCix21WAkQs/1wKfJJ8saJTQPWd0eD5UptURk=,tag:HoB+DTbr/Lz2zsIMxOckag==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqtexnvrf2r7qdwz9a9rc5d79z097vuycugjy00r9dp0u76r0g4qncnya3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbFowZjJ1R0pmMThLK0xj
            dFJORmw0N01NbzNqMDJmRmV3ZStQd1FLdXlnCnp6a09BakpGcmZjV3RlRHlXZGRO
            NlFueklGcXlxWFdPcklnNDRWYi9GSlUKLS0tIEpubGZXNzBhZGF5L0hVcDRuNXVy
            dnBPR3ZrS2gvVmlhVnIwRjZNQW56YXcKUrjc1nxNHRKAWITMDPjGah6Ef4RwCaA/
            j+jR/0bsXXkaiTk9VoFsZhwHh7/Hx8ZvXFfHE0oO3CFtoplRkd69tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-07T00:23:51Z"
    mac: ENC[AES256_GCM,data:a6EepprmRWCoMmGiCU3CN1rLgsrbcEEnGVpqsghTB2FtoPF9giCNa+Irn1/XFSgeOjW3nd24H0pigctfVoCpL3WwXqSSkvta+vrp2jBfQaX1hXIgI4HQq6s2KisD2WgGEFj1WP6Xy6ip+8cYQwRmRH+FHNcx5cEOjwHj00c5Hds=,iv:XRbUoXHW5QNFbgvefTgfSQrmLihyWhJq/R008iMeAoU=,tag:h3BW9Hw11WKQ5JIbWP+kGA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
