apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:RFhDfN7LuirIEYmNYm2YEWpEAHHr5KGuBZxf2Tjl7IDnun2/ErRkvEBzkhd6/BNlZtw9IV2eIukIj+9UHJ89nKjyJrVpQUvqSiHkHvQjBUzJtSiOHcgOAekzhWzIUj6ap7l893CeWrsfDk4OtPKreWGzCtGSel3AxNINyxQmkYHxu2QOqRxDFvuxEqpMqa3uuoATUgV5aPmG971iuKCzIpNxoHp0omaOdE5bJdxbcl7/XdNTawCSGsZVqUVVmcGl+AFdtSb8QI826DkdonBnHcSSbRNClc4m/vIlEbXBjTPCFCPSflxKMa6MV7cGdceqJhJund8wTmRbHMyAL+QVObhm7iv5bO7dfPlolHXjJMREw9libhdbNVGfyiTUR9BN,iv:/rIbWIRxUqrlVLFBieqT4h6t/I4iLH3r3W1CNnsjQ4E=,tag:23U46kU1zO2/D746nyhu9Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:xGelE4Yrr2wOnuIms7VbpDu7NPUV+lVZMDYgwectlWF9YX/KGC9XlaAESBTZ4T5lRAjMpJ78MTugcQp5IzKgrDu0t1qnjQmc5gQtKC1znjCTKaJOo4LlW27jrq8rdsV3rolfR3X6jjFi93cPaAwicV4my3EoHEqIadQ6fjLlIXUY9VO1n7Y3ASB4aI0O/PKfisD2MVy8IwajTOJBbk5NAN4v1p+V1S7hbwZ7FIsorXtqqSsvKf9ChMFjOGPTmN1auZ5xGskNNIzhgfQelw==,iv:BZcGispb8b/FGJPJ9d7H4tu326aWJMFtHAdsWJTLVNc=,tag:SAt/7RhlJIleE/gYdw2vWA==,type:str]
    known_hosts: ENC[AES256_GCM,data:UZiD3u3UgFZMR8WZD0PLPFNOjn7V6+1sYRZhAR65r/ZyG+PLr7V0Msfj6Tu54AZuD2YJG3M2M3veV2YYhclM/5F7c/a540STF0bCc0ka94dBS21XYLIcZ+k5KGIsCBjdgLl0FVymnj49/wrKr0pW3oAz2NkLe9X1yUSpGnZ/kcu3OOogRdrL//fvURAa6FeC6acVQ41RQ8WwlWHSh0D0jns/njv0LppkhkrL,iv:f7Nzbjlmlp3q7h76nBmvcMutpVayPYo3529GViqC7Cw=,tag:CwwqI0ARtR6JakZMhqMNJQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age164t6dj78p0zq6ufhcct37xxntzqqhtwk979kf2zvzcp45lfgqvpsjlqupm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVm00a0JoZm9tc0libFZ3
            UmxEbWRMY0xGR1ptTElQUU8ySkpsMmdxYmswCmsvUXNGaCsvTXpBU2RwSFp3N0k1
            TUd5K3gxUm95YXdJb01kWEdHbkkwRUkKLS0tIEtyYUc2R2RlMU5MQVB0WGx5WW9U
            aWtLMUJ4dENibHgyQklqbTZ5TVRid2sKBAqqJGimJHJI8SPxvACGlUzjrC/1BioM
            GpWfZofx2VEH5Qgd+80B+cT+ZrFwuQDfwxd5aFmMRCtkH3ivTiw4xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T01:58:45Z"
    mac: ENC[AES256_GCM,data:h3tZ40V9XlqUsppk8mCzQUPegUXnMr7EPo84NqPJ4dxN50pZdKkJhQV2zZkIaCc23bagfQhdEGK9LBdD8b8PFvN5B/9YFy6zHZ4McfGZJuZArdT96Y+5EGhN9eDmhTVZAp6nGhPEQFMLS0tGcuuTZ3bl10TgvGYH33nDpGSksUU=,iv:VXjVEYMDPWXfGJGUL8l8lQCoBsancZIXNKfj+8X/5OQ=,tag:SXtTMomqhe2lO/yPaHgg/g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
