apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5cOAWEDDTD7sAT1llKiC3NyvTE2/Fy7zECOc2AyOpZU84P9nEyynpNZcPwQ++bJC45SUoFEtiBtozj/Jf2C9terg1q00Vf+Yfs0BeXPrHtRjyADAYnoltrJEE7fV1nYjpmtyjdwkuuvZ0Jxm58+lpNAD1f+Tdq+Nh7R0VJZtIgcER6+UYmEC0yAwlWz0DFSJwqAM/FAIEL/eJx66kASDZddtMGMFr1ZGIR7UHSneU8E1jNWqm/I85dxnPQMKNJnsqQ9fQ+PU5NMztd/lpiOULKRSPkUUNwzdAw5cDWe6nZS1U3otNkpkrj0KeJA7lfzs753tHQwV5LjtDKNh5M5IOoxC8MY9gUMDgkMokXOSGaT7nVuFCt4cUhdJn5J0akFZ,iv:Gv30wNhMa8DJHdNpEWDAV+hSVxqtb+yxG+hEc5LyLss=,tag:hG7krRRCLpxTknRb+6gIHg==,type:str]
    identity.pub: ENC[AES256_GCM,data:62jWyQAxYgok5Ap9rBtfl/f3afVl8hbHy+RR31RuhdJwNcXGBmLBWFKEEOEDmY+vUQhY6LGP+HcSPGP0Egj5rRPTV9kV721BqZLo2rPHK7wh2eX03yk/Zt1PwaU3Ij92quUw+NvwJqhkj8hIJxQapJH/WiksI7onAHbaCD+1WzoWAn3h3+g0Tu8qk4rFdGu7lcpR0Esar1dbPH1TIuNBqU07s4qKtwF6bn5aFyl0eB6+bezCEOykzw+b7O4Q8xgCbEzJagaTyJLuUuau3w==,iv:BcGGUiQkg6XOeqMuan2YflQQBYnZ9dmf4T5edO75GfY=,tag:v11IPrvxDwGcPoUbnO71Yg==,type:str]
    known_hosts: ENC[AES256_GCM,data:cAIIHozxYHTOnZOTpCywPz6BV+xbvHNZ3+cDeH6trCV0kBf+131QdvNekhs9z0fJhzy/wKC4Gv5++1PlGI9VjWimNX92D+xXT0RbUd8lBNMkJ3UrNXzRffUSsJsq2vP7ZJIjXiq2djs6B/gcRzkOScPODYt5bTquhKO1t4JZBw8HORSkwfqS9i6kwJoyMejx0IknDmbQM/ox3AfD9wvxr059eciLjNZzRvnd,iv:1msUvv+T5LIqELlI35VfmUFFNoOHmvXxb9P+UZL2SMA=,tag:V8Y4A4i1TZ7q3L46BIQL9w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqtexnvrf2r7qdwz9a9rc5d79z097vuycugjy00r9dp0u76r0g4qncnya3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWXE1d2pWUHdidEUvc0hs
            WFpMeENYUDBJT2NqQzUvR0tEY3NuLy9Va1c4CkgvOG1VYVA4WDB4QjZVRWlLRUwx
            Um5iZkhuL1JseDZtT2tQTTFGaDFmNzAKLS0tIEFmNXdGSURvcUhrdkt1ZUZzOW5P
            LzNVTkhBMUZHMUt1WUhBcHV0TG8xTmsKRXzRIy6lnUlJC3ZTalyVZWnTovCgg/Lc
            2ZsWW7yqd0bo+kndL8SnBRX1dUC63i1NcfDUHgKhQpDi4/NSfKQ/DA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-14T15:03:59Z"
    mac: ENC[AES256_GCM,data:HiVaC1i8kHM49nVxtQ+Igory+LdhS0nh1HuXw/OJJCVP2aHczXIDOAS54uxMFugMz/PUW3mr7CHT0lSOjOCF2OuKK0Mp/2yfxAtUo5xxdXMjbc/3toTdT1tfwuxm3IqJ+qv9N0rpyj9DIhLETK46b4TeVa64UqpFo5tZjpGtp3s=,iv:v9o5VLqt/Gu3EppRhXTNOQD36B7iNzK8BBpiFGFf1UI=,tag:IHmtad/dr9aehoAXl102tQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.4
