apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mc-gcli
  namespace: ext-service
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 15.1.10
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Chicago
    global:
      stopAll: false
    service:
      main:
        type: ExternalIP
        externalIP: ${MC_IP}
        ports:
          main:
            enabled: true
            protocol: http
            port: 8082
      mc:
        type: ExternalIP
        externalIP: ${MC_IP}
        ports:
          mc-gcli:
            enabled: true
            protocol: http
            port: 993            
    ingress:
      main:
        enabled: true
        hosts:
          - host: ${DOMAIN_3}
        integrations:
          traefik:
            enabled: true
            # middlewares:
            #   - name: local
            #     namespace: traefik
          certManager:
            enabled: true
            certificateIssuer: cloudflare
                            