---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 32.2.12
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    TZ: America/Chicago
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-nc-app"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"   
    nextcloud:
      credentials:
        initialAdminUser: ${NEXTCLOUD_USER}
        initialAdminPassword: ${NEXTCLOUD_PWD}
      general:
        default_phone_region: US
        accessIP: ${TRAEFIK_IP}
      collabora:
        enabled: true
        username: ${COLLABORA_USER}
        password: ${COLLABORA_PWD}
    persistence:
      # html:    
      #   volsync:
      #     - name: b2
      #       type: restic
      #       credentials: s3
      #       dest:
      #         enabled: true                          
      #       src:
      #         enabled: true
      # config:  
      #   volsync:
      #     - name: b2
      #       type: restic
      #       credentials: s3
      #       dest:
      #         enabled: true                          
      #       src:
      #         enabled: true
      data:
        enabled: true
        type: nfs
        server: ${TRUENAS_IP}
        path: /mnt/data1/nc_userdata
        mountPath: /var/www/html/data               
      # data:     
      #   volsync:
      #     - name: b2
      #       type: restic
      #       credentials: s3
      #       dest:
      #         enabled: true                          
      #       src:
      #         enabled: true
    # cnpg:
    #   main:
    #     password: ${NEXTCLOUD_CNPG_PWD}
    #     cluster:
    #       postgresql:
    #           max_slot_wal_keep_size: 1GB
    #           wal_compression: lz4
    #     #mode: recovery
    #     mode: standalone
    #     backups:
    #       enabled: true
    #       credentials: s3
    #       #revision: "1"
    #       retentionPolicy: "3d"
    #     recovery:
    #       method: object_store
    #       credentials: s3
    #       #revision: "1"  
    redis:
      password: ${NEXTCLOUD_REDIS_PWD}              
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: true
        tls:
          - hosts:
              - nextcloud.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: nextcloud.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix