apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: nextcloud
    namespace: nextcloud
spec:
    interval: 5m
    chart:
        spec:
            # renovate: registryUrl=https://charts.truechartsoci.org
            chart: nextcloud
            version: 32.2.12
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
            interval: 5m
    install:
        createNamespace: true
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    timeout: 20m
    values:
      global:
        stopAll: false
      credentials:
        s3:
          type: s3
          url: "${S3URL}"
          bucket: "${S3PREFIX}-nextcloud-app"
          accessKey: "${S3ID}"
          secretKey: "${S3KEY}"
          encrKey: "${S3KEY}"
      ingress:
        main:
          enabled: true
          integrations:
            traefik:
              enabled: true
              # middlewares:
              #   - name: bouncer 
              #     namespace: traefik
              #   - name: local
              #     namespace: traefik
          hosts:
            - host: next.${DOMAIN_0}
              paths:
                - path: /
                  pathType: Prefix 
          tls:
            - hosts:
                - next.${DOMAIN_0}
              clusterIssuer: domain-0-wildcard
      cnpg:
        main:
          cluster:
            singleNode: false
          pgVersion: 15
          #mode: recovery
          backups:
            enabled: true
            credentials: s3
            scheduledBackups:
              - name: daily-backup
                schedule: "0 5 0 * * *"
                backupOwnerReference: self
                immediate: true
                suspend: false
          recovery:
            method: object_store
            credentials: s3
      persistence:
        config:
          volsync:
          - name: config
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 10 1 * * *
        # data:
        #   enabled: true
        #   type: nfs
        #   path: ${NEXTCLOUD_NFS_PATH}
        #   server: ${CONFIG_TRUENAS_IP}
        data:
          enabled: true
          type: nfs
          server: ${TRUENAS_IP}
          path: /mnt/data1/nc_userdata
          mountPath: /var/www/html/data               
        html:
          volsync:
          - name: html
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 20 1 * * *
      nextcloud:
        collabora:
          enabled: true
          password: "${NEXTCLOUD_PWD}"
        credentials:
          initialAdminPassword: "${NEXTCLOUD_PWD}"
          initialAdminUser: "${NEXTCLOUD_USER}"
        general:
          accessIP: ${TRAEFIK_IP}
          default_phone_region: US
        previews:
          providers:
          - BMP
          - GIF
          - JPEG
          - Krita
          - MarkDown
          - MP3
          - OpenDocument
          - PNG
          - TXT
          - XBitmap