---
# yaml-language-server: schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 15m
  chart:
    spec:
      chart: immich
      version: 17.54.3
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    global:
      stopAll: false

    TZ: America/Chicago

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: pics.${DOMAIN_1}
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: cloudflare
    # persistence:
      # profile:
      #   volsync:
      #     - name: prf
      #       type: restic
      #       credentials: backblaze
      #       dest:
      #         enabled: true
      #       src:
      #         enabled: true
      # thumbs:
      #   volsync:
      #     - name: thn
      #       type: restic
      #       credentials: backblaze
      #       dest:
      #         enabled: true
      #       src:
      #         enabled: true

      # backups:
      #   type: nfs
      #   server: ${TRUENAS_IP}
      #   path: /mnt/data1/immich/backups
      # library:
      #   type: nfs
      #   server: ${TRUENAS_IP}
      #   path: /mnt/data1/immich/library
      # uploads:
      #   type: nfs
      #   server: ${TRUENAS_IP}
      #   path: /mnt/data1/immich/upload
      # video:
      #   type: nfs
      #   server: ${TRUENAS_IP}
      #   path: /mnt/data1/immich/encoded-video

      # external-pics:
      #   enabled: true
      #   type: nfs
      #   server: ${TRUENAS_IP}
      #   path: /mnt/data1/immich/test
      #   mountPath: /usr/src/app/external/test
        
