---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ext-pfsense
  namespace: ext-pfsense
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 15.6.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    TZ: America/Chicago

    service:
      main:
        type: ExternalIP
        externalIP: "192.168.68.1"
        ports:
          main:
            protocol: https
            port: 443

    ingress:
      main:
        enabled: true
        ingressClass: internal
        hosts:
          - host: pfsens.${DOMAIN_1}
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: cloudflare